/*
 * settings.h
 *
 *  Created on: Jun 25, 2025
 *      Author: blondier94
 */

#ifndef SETTINGS_H_
#define SETTINGS_H_

#define TIMEOUT_SPI1_MS 5000
#define USE_SHIFTING_IN_SetPinFromArray 0

/* machine_main */
#define DEBUG_SEND_BY_CAN_MACHINE_CONTROL 1
#define DEBUG_HARDWARE_CONTROL_DISABLED 0
#define TEMPERATURE_LOOP_HARDWARE_CONTROL_DAC_DISABLED 0
#define HARDWARE_CONTROL_TEMPERATURE_LOOP_RAMP_BIT_DISABLED 0
#define HARDWARE_CONTROL_TEMPERATURE_LOOP_DISABLED 0
#define HARDWARE_CONTROL_DAC_DISABLED 0
#define HARDWARE_CONTROL_SPI_DISABLED 0
#define HARDWARE_CONTROL_GPIO_DISABLED 0

#define USE_SMALLER_STEPS_NEAR_DAC_TARGET 1

#define TEMPERATURE_LOOP_CORRECT_BY_READING_ENABLED 0

/* AFE_functions */
#define USE_STACK_FOR_BUFFER 0
#define ADC_MEASUREMENT_RAW_SIZE_MAX 128
#define AFE_NUMBER_OF_CHANNELS 8
#define AFE_NUMBER_OF_SUBDEVICES 2
#define ADC_MEASUREMENT_RAW_DEFAULT_DT_MS 1000

#define AFE_DAC_MAX 0x0FFF
#define AFE_DAC_START 0x0FFF

#define AFE_REGULATOR_SET_DEFAULT_PARAMS 0
#define AFE_REGULATOR_SET_DEFAULT_RAMP 1
#define AFE_REGULATOR_DEFAULT_RAMP_ENABLED 1
#if AFE_REGULATOR_SET_DEFAULT_PARAMS
#define AFE_REGULATOR_DEFAULT_a_dac (-259.602373913043f)
#define AFE_REGULATOR_DEFAULT_b_dac (16530.5430434783f)
#define AFE_REGULATOR_DEFAULT_dV_dT (0.05f)
#define AFE_REGULATOR_DEFAULT_T0 (25.0f)
#define AFE_REGULATOR_DEFAULT_U0 (55.0f)
#define AFE_REGULATOR_DEFAULT_U_offset (0.0f)
#define AFE_REGULATOR_DEFAULT_dT (1.0f)
#define AFE_REGULATOR_DEFAULT_T_old (-100.0f)
#endif // AFE_REGULATOR_SET_DEFAULT_PARAMS
#if AFE_REGULATOR_SET_DEFAULT_RAMP
#define AFE_REGULATOR_DEFAULT_ramp_bit_step (100U)
#define AFE_REGULATOR_DEFAULT_ramp_bit_step_every_ms (100U)
#endif // AFE_REGULATOR_SET_DEFAULT_RAMP

#define NUMBER_OF_AD8402_CHANNELS 2

#define USE_ARIMA 0

/* can_functions */
#if HEADLESS_AFE_CAN_ID
#else
#define AFE_CAN_ID 41
#endif

#define CAN_ID_IN_MSG ((1<<10) | (AFE_CAN_ID << 2))

#define CAN_MSG_LIFETIME_MS 10000
#define CAN_BUFFER_SIZE 64
#define CAN_MSG_RECIEVED_TIMEOUT_MS 5000
#define USE_CAN_MSG_BURST_DELAY_MS 1
#define WATCHDOG_FOR_CAN_RECIEVER_ENABLED 1


#endif /* SETTINGS_H_ */
